### ISSUE TITLE
应当给白色主题增加边框或阴影

### ISSUE THREAD

**Issue by pkptzx** [bilibili-ayang/ChatGPT-Desktop#14]
应当给白色主题增加边框或阴影。
当我在浏览白色网页或其他应用时，焦点不在chatgtp-desktop上时，边框会隐藏，这时候我分不清天与地。
![image](https://user-images.githubusercontent.com/4339676/226188489-cc51c04c-4bf9-44ec-babe-a60445a0d42f.png)

**Comment by bilibili-ayang** [comment]
感谢反馈，windows 系统已默认添加窗口阴影，会在下个版本更新！敬请关注！
