### ISSUE TITLE
滚动条丑and遮挡置顶按钮for windows

### ISSUE THREAD

**Issue by pkptzx** [bilibili-ayang/ChatGPT-Desktop#16]
![image](https://user-images.githubusercontent.com/4339676/226189229-ffee0c38-4b28-4cc6-ac0e-a2171f1002a0.png)

**Comment by bilibili-ayang** [comment]
> ![image](https://user-images.githubusercontent.com/4339676/226189229-ffee0c38-4b28-4cc6-ac0e-a2171f1002a0.png)

滚动条已修复，需要等下次发版！
