### ISSUE TITLE
主界面一直处于置顶状态，没有关闭按钮。

### ISSUE THREAD

**Issue by Echo-zyk** [bilibili-ayang/ChatGPT-Desktop#172]
1. 主页面 希望增加关闭 最小化 最大化按钮。
2.应用一直处于置顶，点击其他页面切换时还必须还得先手动隐藏才行。

**Comment by orangelckc** [comment]
我们的设计初衷是配合快捷键进行使用，随时唤出和隐藏
您也可以在软件顶部的拖动条进行双击，取消固定在桌面，这样当软件窗口失去焦点，就会自动隐藏
![image](https://user-images.githubusercontent.com/48410934/229347757-41e31f43-9daf-4493-8014-7d80e50f1313.png)

**Comment by orangelckc** [comment]
@Echo-zyk 
我们使用的输出方式与OPENAI官网相同，是流式输出，当窗口隐藏后，数据流就会暂停，这个我们没有办法进行修改，抱歉带来不便。

**Comment by iabood09** [comment]
اشكرك على مجهودك وتخليصك لنا العناء
