### ISSUE TITLE
添加角色的输入框被遮住了for windows

### ISSUE THREAD

**Issue by pkptzx** [bilibili-ayang/ChatGPT-Desktop#19]
有时候不知道怎么点的没遮住，但大概率99.9999%被遮住
![image](https://user-images.githubusercontent.com/4339676/226190175-707d5a6e-18a6-4861-9e4b-005daeb4f564.png)

**Comment by orangelckc** [comment]
确实，输入/后添加角色，当前的列表未出现变化，并没有出现添加角色的页面

https://user-images.githubusercontent.com/48410934/226213356-8db1b76b-b729-46b7-b981-2c175c8d2c0c.mp4

**Comment by bilibili-ayang** [comment]
> 有时候不知道怎么点的没遮住，但大概率99.9999%被遮住 ![image](https://user-images.githubusercontent.com/4339676/226190175-707d5a6e-18a6-4861-9e4b-005daeb4f564.png)

感谢大佬的反馈呀，已经修复啦！
