### ISSUE TITLE
https://download.ayangweb.cn/ 网站开源了吗？

### ISSUE THREAD

**Issue by kjxbyz** [bilibili-ayang/ChatGPT-Desktop#239]
https://download.ayangweb.cn/ 网站开源了吗？

**Comment by ayangweb** [comment]
这个没有哦！

**Comment by kjxbyz** [comment]
我看有开源的类似的项目，tauri-update-serveer

**Comment by ayangweb** [comment]
> tauri-update-serveer

是的，可以参考别的大佬的库哦，我们这个没有开源！

**Comment by kjxbyz** [comment]
> > tauri-update-serveer
> 
> 是的，可以参考别的大佬的库哦，我们这个没有开源！

还是等有时间了自己实现一个吧。
