### ISSUE TITLE
禁用鼠标右键与内置快捷键

### ISSUE THREAD

**Issue by pkptzx** [bilibili-ayang/ChatGPT-Desktop#24]
再一次.....

<details>
<summary>只在发布的版本禁止右键</summary>

```javascript
  if (import.meta.env.PROD) {
    document.addEventListener('contextmenu', (event) => event.preventDefault());
  }
```
</details>
<details>
<summary>屏蔽一些浏览器默认的快捷键</summary>

比如:ctrl+p,ctrl+u,ctrl+f,ctrl+g
```javascript
  document.onkeydown = function(event) {
    if(event.ctrlKey == true && event.code == 'KeyP') {
        console.log('Ctrl + p');
        event.preventDefault();
    }
    if(event.ctrlKey == true && event.code == 'KeyU') {
        console.log('Ctrl + u');
        event.preventDefault();
    }
    if(event.ctrlKey == true && event.code == 'KeyG') {
        console.log('Ctrl + g');
        event.preventDefault();
    }
}
```
</details>

**Comment by orangelckc** [comment]
全部屏蔽的话，会不会影响文字的框选？
或者说加入自定义右键菜单的功能？

**Comment by bilibili-ayang** [comment]
@pkptzx @orangelckc 禁用右键只在未选择文本才禁用这个功能已经添加

@pkptzx 这些默认快捷键会在 windows 触发一些操作是吗？这边 mac 我看没有任何反应！

**Comment by bilibili-ayang** [comment]
> > @pkptzx @orangelckc 禁用右键只在未选择文本才禁用这个功能已经添加
> > @pkptzx 这些默认快捷键会在 windows 触发一些操作是吗？这边 mac 我看没有任何反应！
> 
> mac肯定也有,需要查一下.或者直接在浏览器里看一眼快捷键. 比如: win的`Ctrl + u`在mac下是`Command+Option+U`

ok，我这边测试一下！

**Comment by bilibili-ayang** [comment]
> 再一次.....
> 
> 只在发布的版本禁止右键
> 屏蔽一些浏览器默认的快捷键

大佬，最新上传的代码已经禁用了快捷键，您那边如果方便的话可以测试一下！
