### ISSUE TITLE
bug: stream error

### ISSUE THREAD

**Issue by wegi8** [bilibili-ayang/ChatGPT-Desktop#26]
<img width="361" alt="image" src="https://user-images.githubusercontent.com/43628500/226230885-a3909356-47a0-424f-abae-3a6cf571b2ba.png">

Feature: The api key should be insert before the chat

**Comment by wegi8** [comment]
Show the GPT Versions on you md

**Comment by bilibili-ayang** [comment]
> <img alt="image" width="361" src="https://user-images.githubusercontent.com/43628500/226230885-a3909356-47a0-424f-abae-3a6cf571b2ba.png">
> 
> Feature: The api key should be insert before the chat

感谢反馈，此问题是 api key 填写错误 或者 网络问题，新版本已加入提示！

**Comment by wegi8** [comment]
11
