### ISSUE TITLE
已经填了key，但是还是

### ISSUE THREAD

**Issue by wangllxxxx** [bilibili-ayang/ChatGPT-Desktop#32]
![1679301760090](https://user-images.githubusercontent.com/122505992/226288607-2d44fbfd-b2de-4b79-a0d9-bc7171bed380.png)

![1679301768752](https://user-images.githubusercontent.com/122505992/226288655-61250161-e6c9-47bd-a43e-6ccc1e433286.png)
这是什么原因

**Comment by q1591995136** [comment]
我也是填了key但还是提示要我填

**Comment by orangelckc** [comment]
@q1591995136 @wangllxxxx  麻烦反馈下使用的版本

**Comment by wangllxxxx** [comment]
@orangelckc 0.0.2

**Comment by wangllxxxx** [comment]
@orangelckc 0.0.3没这个问题了

**Comment by orangelckc** [comment]
可以升级下新的[0.0.3](https://github.com/bilibili-ayang/ChatGPT-Desktop/releases/tag/v0.0.3)， 目前项目刚刚发版，更新的比较快，给您带来不便，希望理解

**Comment by orangelckc** [comment]
> @orangelckc 0.0.3没这个问题了

好的 那我关闭这个issue了
