### ISSUE TITLE
程序可以多开

### ISSUE THREAD

**Issue by Daydreamcgy** [bilibili-ayang/ChatGPT-Desktop#53]
![image](https://user-images.githubusercontent.com/61179540/226649811-78aa8014-6d30-4c0a-9985-541a2c8fdb68.png)

会导致最先开的程序脱离了快捷键的控制。

**Comment by Daydreamcgy** [comment]
好吧，也不知道算不算bug，没准还是优点。

**Comment by orangelckc** [comment]
windows 上多开的问题已修复，mac默认是只支持单例模式，除非手动使用termin开启，目前官方并没有支持mac的单例模式，详见 [ISSUE](https://github.com/tauri-apps/plugins-workspace/issues/287)，后续如果需要可以再把这个issue打开
